spring:
  application:
    name: almacenes
  datasource:
    url: jdbc:postgresql://localhost:5432/almacen_db
    username: postgres
    password: david123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # 'validate' garantiza que Spring Boot respete tu script SQL sin borrar ni alterar tus tablas
      ddl-auto: validate
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

server:
  port: 8080